### ISSUE TITLE
How can i make this work with repl.it?

### ISSUE THREAD

**Issue by Joshii01** [Vexed-Nz/GimKit-Flooder#1]
Hey there! how can i make this project work with <a href=https://repl.it> repl.it</a> ?

**Comment by Vexed-Nz** [comment]
Hello @Joshii01 I do not have a clear answer at the moment for using the project in since it uses a automated browser and repl.it can't have heavy programs on there server side you may want to contact to email repl.it to see if it is possible to use a automate browser in there site other than I can't really tell you much since I haven't done something like that.

- Have a Nice day.
